version: '3.5'

services:

  server:
    build:
      context: ./server
      dockerfile: /home/cc/Documents/signzy/server/DockerFile
    ports:
      - 3000:3000
    networks:
      Signzy_network:
        aliases:
          - service.local

  web:
    build:
      context: ./web
      dockerfile: /home/cc/Documents/signzy/web/DockerFile
    ports:
      - 4200:4200
    networks:
      - Signzy_network

networks:
  Signzy_network:
    driver: bridge

